-- ============================================================================
-- Project: Kinder Pets - Pet Adoption Management System (DBMS DA2)
-- File: 01_schema.sql
-- Description: Oracle-compatible DDL schema definition for 12 DA1 entities.
-- Target RDBMS: Oracle Database 19c / 21c / 23ai (also compatible with Oracle 12c+)
-- ============================================================================

-- Drop tables in reverse order of foreign key dependency
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name IN (
        'SHELTER_DECISION', 'ADOPTION_APPLICATION', 'MATCH', 'SWIPE',
        'PREFERRED_BREED', 'ADOPTER_PREFERENCE', 'PET_PHOTO', 'PET',
        'BREED', 'SHELTER_STAFF', 'ADOPTER', 'SHELTER'
    )) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- 1. SHELTER
-- Represents registered animal shelters providing rescue and adoption facilities.
CREATE TABLE SHELTER (
    shelter_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_name    VARCHAR2(100) NOT NULL,
    license_no      VARCHAR2(50)  NOT NULL UNIQUE,
    city            VARCHAR2(60)  NOT NULL
);

-- 2. SHELTER_STAFF
-- Employees / caretakers managing shelters, pet reviews, and adoption approvals.
CREATE TABLE SHELTER_STAFF (
    staff_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_id      NUMBER(10)    NOT NULL,
    staff_name      VARCHAR2(80)  NOT NULL,
    role            VARCHAR2(50)  NOT NULL,
    CONSTRAINT fk_staff_shelter FOREIGN KEY (shelter_id) 
        REFERENCES SHELTER(shelter_id) ON DELETE CASCADE
);

-- 3. BREED
-- Master reference table for pet breeds and their biological species.
CREATE TABLE BREED (
    breed_name      VARCHAR2(60) PRIMARY KEY,
    species         VARCHAR2(30) NOT NULL
);

-- 4. PET
-- Core pet entity available or processed for adoption.
CREATE TABLE PET (
    pet_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shelter_id      NUMBER(10)    NOT NULL,
    breed_name      VARCHAR2(60)  NOT NULL,
    pet_name        VARCHAR2(60)  NOT NULL,
    gender          VARCHAR2(10)  NOT NULL,
    age_months      NUMBER(4)     NOT NULL,
    size            VARCHAR2(20)  NOT NULL,
    behaviour_desc  VARCHAR2(500),
    lifestyle_desc  VARCHAR2(500),
    status          VARCHAR2(20)  DEFAULT 'Available' NOT NULL,
    CONSTRAINT fk_pet_shelter FOREIGN KEY (shelter_id) 
        REFERENCES SHELTER(shelter_id) ON DELETE CASCADE,
    CONSTRAINT fk_pet_breed FOREIGN KEY (breed_name) 
        REFERENCES BREED(breed_name) ON DELETE RESTRICT,
    CONSTRAINT chk_pet_gender CHECK (gender IN ('Male', 'Female', 'Unknown')),
    CONSTRAINT chk_pet_size CHECK (size IN ('Small', 'Medium', 'Large', 'Extra Large')),
    CONSTRAINT chk_pet_status CHECK (status IN ('Available', 'Pending', 'Adopted', 'Fostered')),
    CONSTRAINT chk_pet_age CHECK (age_months >= 0)
);

-- 5. PET_PHOTO
-- Multi-image support for pet profiles to visually showcase pets.
CREATE TABLE PET_PHOTO (
    photo_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          NUMBER(10)    NOT NULL,
    photo_url       VARCHAR2(500) NOT NULL,
    is_primary      NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT fk_photo_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_photo_primary CHECK (is_primary IN (0, 1))
);

-- 6. ADOPTER
-- Prospective adopters searching and applying for pets.
CREATE TABLE ADOPTER (
    adopter_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name       VARCHAR2(80)  NOT NULL,
    email           VARCHAR2(100) NOT NULL UNIQUE,
    phone           VARCHAR2(20)  NOT NULL,
    city            VARCHAR2(60)  NOT NULL,
    state           VARCHAR2(60)  NOT NULL
);

-- 7. ADOPTER_PREFERENCE
-- 1-to-1 extension capturing adopter preferences for automated matching filters.
CREATE TABLE ADOPTER_PREFERENCE (
    adopter_id          NUMBER(10) PRIMARY KEY,
    preferred_species   VARCHAR2(30),
    min_age_months      NUMBER(4)    DEFAULT 0,
    max_age_months      NUMBER(4)    DEFAULT 240,
    preferred_size      VARCHAR2(20),
    CONSTRAINT fk_pref_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT chk_pref_age_range CHECK (min_age_months <= max_age_months),
    CONSTRAINT chk_pref_size CHECK (preferred_size IS NULL OR preferred_size IN ('Small', 'Medium', 'Large', 'Extra Large'))
);

-- 8. PREFERRED_BREED
-- Many-to-Many composite table mapping adopters to multiple desired breeds.
CREATE TABLE PREFERRED_BREED (
    adopter_id      NUMBER(10)   NOT NULL,
    breed_name      VARCHAR2(60) NOT NULL,
    PRIMARY KEY (adopter_id, breed_name),
    CONSTRAINT fk_pb_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_pb_breed FOREIGN KEY (breed_name) 
        REFERENCES BREED(breed_name) ON DELETE CASCADE
);

-- 9. SWIPE
-- Records Tinder-style user interactions (LEFT = Skip, RIGHT = Interested).
CREATE TABLE SWIPE (
    swipe_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adopter_id      NUMBER(10)   NOT NULL,
    pet_id          NUMBER(10)   NOT NULL,
    direction       VARCHAR2(10) NOT NULL,
    swiped_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_swipe_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_swipe_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_swipe_direction CHECK (direction IN ('LEFT', 'RIGHT')),
    CONSTRAINT uq_adopter_pet_swipe UNIQUE (adopter_id, pet_id)
);

-- 10. MATCH
-- Generated when mutual interest / qualification is established.
CREATE TABLE MATCH (
    match_id        NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adopter_id      NUMBER(10)   NOT NULL,
    pet_id          NUMBER(10)   NOT NULL,
    matched_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT fk_match_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_match_status CHECK (status IN ('Active', 'Applied', 'Closed')),
    CONSTRAINT uq_adopter_pet_match UNIQUE (adopter_id, pet_id)
);

-- 11. ADOPTION_APPLICATION
-- Formal application submitted by a matched adopter for verification & home visit.
CREATE TABLE ADOPTION_APPLICATION (
    application_id      NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    match_id            NUMBER(10)   NOT NULL UNIQUE,
    staff_id            NUMBER(10),
    home_visit_date     DATE         NOT NULL,
    application_status  VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    submitted_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_app_match FOREIGN KEY (match_id) 
        REFERENCES MATCH(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_app_staff FOREIGN KEY (staff_id) 
        REFERENCES SHELTER_STAFF(staff_id) ON DELETE SET NULL,
    CONSTRAINT chk_app_status CHECK (application_status IN ('Pending', 'Under Review', 'Approved', 'Rejected'))
);

-- 12. SHELTER_DECISION
-- Final adjudication recorded by shelter staff with approval or rejection.
CREATE TABLE SHELTER_DECISION (
    decision_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id          NUMBER(10)   NOT NULL,
    adopter_id      NUMBER(10)   NOT NULL,
    decision        VARCHAR2(20) NOT NULL,
    staff_id        NUMBER(10)   NOT NULL,
    decided_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT fk_dec_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT fk_dec_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_dec_staff FOREIGN KEY (staff_id) 
        REFERENCES SHELTER_STAFF(staff_id) ON DELETE CASCADE,
    CONSTRAINT chk_decision_val CHECK (decision IN ('Approved', 'Rejected'))
);
