-- ============================================================================
-- Project: Kinder Pets - Pet Adoption Management System (DBMS DA2)
-- File: 01_schema.sql
-- Description: Oracle SQL DDL Schema Definition for all 12 DA1 Entities.
-- Target RDBMS: Oracle Database 19c / 21c / 23ai Free
-- 
-- DA1 Entity Mapping (Exactly 12 Tables):
--   1. SHELTER              - Animal shelters housing pets
--   2. SHELTER_STAFF        - Staff members employed at shelters
--   3. BREED                - Master species and breed catalog
--   4. PET                  - Pet profiles available/processed for adoption
--   5. PET_PHOTO            - Multi-image gallery for pets
--   6. ADOPTER              - Registered prospective pet adopters
--   7. ADOPTER_PREFERENCE   - 1:1 Adopter preference criteria (age, size, species)
--   8. PREFERRED_BREED      - M:N Bridge between adopters and preferred breeds
--   9. SWIPE                - Tinder-style swipe actions (LEFT/RIGHT)
--  10. PET_MATCH            - DA1 MATCH entity (named PET_MATCH to avoid Oracle reserved keyword MATCH)
--  11. ADOPTION_APPLICATION - Formal adoption applications submitted by matched adopters
--  12. SHELTER_DECISION     - Shelter staff adjudication audit log (Approved/Rejected)
-- ============================================================================

SET FEEDBACK ON;
SET ECHO OFF;

-- ----------------------------------------------------------------------------
-- Safe Re-runnable Table Drop Logic
-- Drops existing tables in reverse dependency order with CASCADE CONSTRAINTS.
-- ----------------------------------------------------------------------------
BEGIN
    FOR t IN (
        SELECT table_name 
        FROM user_tables 
        WHERE table_name IN (
            'SHELTER_DECISION',
            'ADOPTION_APPLICATION',
            'PET_MATCH',
            'MATCH',
            'SWIPE',
            'PREFERRED_BREED',
            'ADOPTER_PREFERENCE',
            'PET_PHOTO',
            'PET',
            'BREED',
            'SHELTER_STAFF',
            'ADOPTER',
            'SHELTER'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE "' || t.table_name || '" CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- ============================================================================
-- 1. SHELTER
-- Represents physical animal shelters providing rescue, care, and adoption.
-- ============================================================================
CREATE TABLE SHELTER (
    shelter_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    shelter_name    VARCHAR2(100) NOT NULL,
    license_no      VARCHAR2(50)  NOT NULL,
    city            VARCHAR2(60)  NOT NULL,
    CONSTRAINT pk_shelter PRIMARY KEY (shelter_id),
    CONSTRAINT uq_shelter_license UNIQUE (license_no)
);

-- ============================================================================
-- 2. SHELTER_STAFF
-- Shelter employees and veterinarians who manage animals and adoption reviews.
-- ============================================================================
CREATE TABLE SHELTER_STAFF (
    staff_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    shelter_id      NUMBER(10)    NOT NULL,
    staff_name      VARCHAR2(80)  NOT NULL,
    role            VARCHAR2(50)  NOT NULL,
    CONSTRAINT pk_shelter_staff PRIMARY KEY (staff_id),
    CONSTRAINT fk_staff_shelter FOREIGN KEY (shelter_id) 
        REFERENCES SHELTER(shelter_id) ON DELETE CASCADE
);

-- ============================================================================
-- 3. BREED
-- Master reference table for taxonomy (breed and biological species).
-- ============================================================================
CREATE TABLE BREED (
    breed_name      VARCHAR2(60),
    species         VARCHAR2(30)  NOT NULL,
    CONSTRAINT pk_breed PRIMARY KEY (breed_name),
    CONSTRAINT chk_breed_species CHECK (species IN ('Dog', 'Cat', 'Other'))
);

-- ============================================================================
-- 4. PET
-- Core animal entity cataloged under a shelter with behavioral attributes.
-- ============================================================================
CREATE TABLE PET (
    pet_id          NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    shelter_id      NUMBER(10)    NOT NULL,
    breed_name      VARCHAR2(60)  NOT NULL,
    pet_name        VARCHAR2(60)  NOT NULL,
    gender          VARCHAR2(10)  NOT NULL,
    age_months      NUMBER(4)     NOT NULL,
    "SIZE"          VARCHAR2(20)  NOT NULL,
    behaviour_desc  VARCHAR2(500),
    lifestyle_desc  VARCHAR2(500),
    status          VARCHAR2(20)  DEFAULT 'Available' NOT NULL,
    CONSTRAINT pk_pet PRIMARY KEY (pet_id),
    CONSTRAINT fk_pet_shelter FOREIGN KEY (shelter_id) 
        REFERENCES SHELTER(shelter_id) ON DELETE CASCADE,
    CONSTRAINT fk_pet_breed FOREIGN KEY (breed_name) 
        REFERENCES BREED(breed_name),
    CONSTRAINT chk_pet_gender CHECK (gender IN ('Male', 'Female', 'Unknown')),
    CONSTRAINT chk_pet_size CHECK ("SIZE" IN ('Small', 'Medium', 'Large', 'Extra Large')),
    CONSTRAINT chk_pet_status CHECK (status IN ('Available', 'Pending', 'Adopted', 'Fostered')),
    CONSTRAINT chk_pet_age CHECK (age_months >= 0)
);

-- ============================================================================
-- 5. PET_PHOTO
-- 1-to-Many gallery images for pets with a primary display flag.
-- ============================================================================
CREATE TABLE PET_PHOTO (
    photo_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    pet_id          NUMBER(10)    NOT NULL,
    photo_url       VARCHAR2(500) NOT NULL,
    is_primary      NUMBER(1)     DEFAULT 0 NOT NULL,
    CONSTRAINT pk_pet_photo PRIMARY KEY (photo_id),
    CONSTRAINT fk_photo_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_photo_primary CHECK (is_primary IN (0, 1))
);

-- ============================================================================
-- 6. ADOPTER
-- Registered prospective pet adopters browsing and applying for pets.
-- ============================================================================
CREATE TABLE ADOPTER (
    adopter_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    full_name       VARCHAR2(80)  NOT NULL,
    email           VARCHAR2(100) NOT NULL,
    phone           VARCHAR2(20)  NOT NULL,
    city            VARCHAR2(60)  NOT NULL,
    state           VARCHAR2(60)  NOT NULL,
    CONSTRAINT pk_adopter PRIMARY KEY (adopter_id),
    CONSTRAINT uq_adopter_email UNIQUE (email)
);

-- ============================================================================
-- 7. ADOPTER_PREFERENCE
-- 1-to-1 extension capturing adopter preferences for automated matchmaking.
-- ============================================================================
CREATE TABLE ADOPTER_PREFERENCE (
    adopter_id          NUMBER(10),
    preferred_species   VARCHAR2(30),
    min_age_months      NUMBER(4)    DEFAULT 0 NOT NULL,
    max_age_months      NUMBER(4)    DEFAULT 240 NOT NULL,
    preferred_size      VARCHAR2(20),
    CONSTRAINT pk_adopter_preference PRIMARY KEY (adopter_id),
    CONSTRAINT fk_pref_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT chk_pref_age_range CHECK (min_age_months <= max_age_months AND min_age_months >= 0),
    CONSTRAINT chk_pref_size CHECK (preferred_size IS NULL OR preferred_size IN ('Small', 'Medium', 'Large', 'Extra Large')),
    CONSTRAINT chk_pref_species CHECK (preferred_species IS NULL OR preferred_species IN ('Dog', 'Cat', 'Other'))
);

-- ============================================================================
-- 8. PREFERRED_BREED
-- Many-to-Many composite table mapping adopters to multiple desired breeds.
-- ============================================================================
CREATE TABLE PREFERRED_BREED (
    adopter_id      NUMBER(10)   NOT NULL,
    breed_name      VARCHAR2(60) NOT NULL,
    CONSTRAINT pk_preferred_breed PRIMARY KEY (adopter_id, breed_name),
    CONSTRAINT fk_pb_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_pb_breed FOREIGN KEY (breed_name) 
        REFERENCES BREED(breed_name) ON DELETE CASCADE
);

-- ============================================================================
-- 9. SWIPE
-- Records Tinder-style user interactions (LEFT = Skip, RIGHT = Interested).
-- ============================================================================
CREATE TABLE SWIPE (
    swipe_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    adopter_id      NUMBER(10)   NOT NULL,
    pet_id          NUMBER(10)   NOT NULL,
    direction       VARCHAR2(10) NOT NULL,
    swiped_at       TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_swipe PRIMARY KEY (swipe_id),
    CONSTRAINT fk_swipe_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_swipe_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_swipe_direction CHECK (direction IN ('LEFT', 'RIGHT')),
    CONSTRAINT uq_adopter_pet_swipe UNIQUE (adopter_id, pet_id)
);

-- ============================================================================
-- 10. PET_MATCH (Represents DA1 'MATCH' Entity)
-- NOTE: In Oracle SQL, 'MATCH' is a reserved keyword (used in MATCH_RECOGNIZE).
-- Per DA2 requirements, this physical table is named PET_MATCH to ensure full
-- Oracle compatibility while representing the logical DA1 MATCH entity.
-- ============================================================================
CREATE TABLE PET_MATCH (
    match_id        NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    adopter_id      NUMBER(10)   NOT NULL,
    pet_id          NUMBER(10)   NOT NULL,
    matched_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status          VARCHAR2(20) DEFAULT 'Active' NOT NULL,
    CONSTRAINT pk_pet_match PRIMARY KEY (match_id),
    CONSTRAINT fk_match_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_match_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT chk_match_status CHECK (status IN ('Active', 'Applied', 'Closed')),
    CONSTRAINT uq_adopter_pet_match UNIQUE (adopter_id, pet_id)
);

-- ============================================================================
-- 11. ADOPTION_APPLICATION
-- Formal application submitted by a matched adopter for home visit review.
-- ============================================================================
CREATE TABLE ADOPTION_APPLICATION (
    application_id      NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    match_id            NUMBER(10)   NOT NULL,
    staff_id            NUMBER(10),
    home_visit_date     DATE         NOT NULL,
    application_status  VARCHAR2(20) DEFAULT 'Pending' NOT NULL,
    submitted_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_adoption_application PRIMARY KEY (application_id),
    CONSTRAINT uq_app_match UNIQUE (match_id),
    CONSTRAINT fk_app_match FOREIGN KEY (match_id) 
        REFERENCES PET_MATCH(match_id) ON DELETE CASCADE,
    CONSTRAINT fk_app_staff FOREIGN KEY (staff_id) 
        REFERENCES SHELTER_STAFF(staff_id) ON DELETE SET NULL,
    CONSTRAINT chk_app_status CHECK (application_status IN ('Pending', 'Under Review', 'Approved', 'Rejected'))
);

-- ============================================================================
-- 12. SHELTER_DECISION
-- Formal adjudication logged by shelter staff (Approved or Rejected).
-- ============================================================================
CREATE TABLE SHELTER_DECISION (
    decision_id     NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100 INCREMENT BY 1),
    pet_id          NUMBER(10)   NOT NULL,
    adopter_id      NUMBER(10)   NOT NULL,
    decision        VARCHAR2(20) NOT NULL,
    staff_id        NUMBER(10)   NOT NULL,
    decided_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT pk_shelter_decision PRIMARY KEY (decision_id),
    CONSTRAINT fk_dec_pet FOREIGN KEY (pet_id) 
        REFERENCES PET(pet_id) ON DELETE CASCADE,
    CONSTRAINT fk_dec_adopter FOREIGN KEY (adopter_id) 
        REFERENCES ADOPTER(adopter_id) ON DELETE CASCADE,
    CONSTRAINT fk_dec_staff FOREIGN KEY (staff_id) 
        REFERENCES SHELTER_STAFF(staff_id) ON DELETE CASCADE,
    CONSTRAINT chk_decision_val CHECK (decision IN ('Approved', 'Rejected'))
);

-- ============================================================================
-- Performance Indexes on Foreign Keys and Query Keys
-- ============================================================================
CREATE INDEX idx_staff_shelter ON SHELTER_STAFF(shelter_id);
CREATE INDEX idx_pet_shelter   ON PET(shelter_id);
CREATE INDEX idx_pet_breed     ON PET(breed_name);
CREATE INDEX idx_pet_status    ON PET(status);
CREATE INDEX idx_photo_pet     ON PET_PHOTO(pet_id);
CREATE INDEX idx_swipe_adopter ON SWIPE(adopter_id);
CREATE INDEX idx_swipe_pet     ON SWIPE(pet_id);
CREATE INDEX idx_match_adopter ON PET_MATCH(adopter_id);
CREATE INDEX idx_match_pet     ON PET_MATCH(pet_id);
-- (match_id in ADOPTION_APPLICATION is already indexed by its UNIQUE constraint)
CREATE INDEX idx_app_staff     ON ADOPTION_APPLICATION(staff_id);
CREATE INDEX idx_dec_pet       ON SHELTER_DECISION(pet_id);
CREATE INDEX idx_dec_adopter   ON SHELTER_DECISION(adopter_id);
CREATE INDEX idx_dec_staff     ON SHELTER_DECISION(staff_id);

-- Verify all 12 tables exist
SELECT table_name 
FROM user_tables 
WHERE table_name IN (
    'SHELTER', 'SHELTER_STAFF', 'BREED', 'PET', 'PET_PHOTO',
    'ADOPTER', 'ADOPTER_PREFERENCE', 'PREFERRED_BREED',
    'SWIPE', 'PET_MATCH', 'ADOPTION_APPLICATION', 'SHELTER_DECISION'
)
ORDER BY table_name;
